In [1]:
import pandas as pd
import numpy as np

- bike.csv 파일을 읽고 데이터프레임(변수명:df)으로 저장

In [2]:
df = pd.read_csv("bike.csv",parse_dates=['datetime'])

season 컬럼

- season 종류 별 데이터 건수 출력

In [5]:
df.head()

datetime  season  holiday  workingday  weather  temp   atemp  \
0 2011-01-01 00:00:00       1        0           0        1  9.84  14.395   
1 2011-01-01 01:00:00       1        0           0        1  9.02  13.635   
2 2011-01-01 02:00:00       1        0           0        1  9.02  13.635   
3 2011-01-01 03:00:00       1        0           0        1  9.84  14.395   
4 2011-01-01 04:00:00       1        0           0        1  9.84  14.395   

   humidity  windspeed  casual  registered  count  
0        81        0.0       3          13     16  
1        80        0.0       8          32     40  
2        80        0.0       5          27     32  
3        75        0.0       3          10     13  
4        75        0.0       0           1      1

In [12]:
df.season.value_counts()

4    2734
3    2733
2    2733
1    2686
Name: season, dtype: int64

temp 컬럼

- 최대, 최소, 평균, 중앙값, 표준편차 출력

- 월별 temp 평균 온도 출력

- temp 컬럼 값을 0-10, 10-20, 20-30 구간으로 나눈다음, 구간별 데이터 건수를 출력

In [8]:
df.temp.describe()

count    10886.00000
mean        20.23086
std          7.79159
min          0.82000
25%         13.94000
50%         20.50000
75%         26.24000
max         41.00000
Name: temp, dtype: float64

In [16]:
df.groupby(df['datetime'].dt.month)['temp'].mean()

datetime
1      9.840000
2     11.798535
3     15.902175
4     18.718372
5     22.674079
6     27.064496
7     30.841711
8     29.736689
9     25.779032
10    20.933853
11    15.185752
12    13.831206
Name: temp, dtype: float64

In [19]:
pd.cut(df.temp,bins=[0,10,20,30]).value_counts()

(20, 30]    4334
(10, 20]    4049
(0, 10]     1259
Name: temp, dtype: int64

windspeed 컬럼

- 0으로 되어 있는 값의 개수를 세어 출력

- 월별 windspeed 평균 풍속 출력(0 제외)


In [40]:
df.windspeed.value_counts()[0]

1313

In [46]:
df.groupby(df['datetime'].dt.month)['windspeed'].mean()

datetime
1     14.582959
2     13.963707
3     15.363249
4     15.581090
5     12.293956
6     12.348930
7     11.019928
8     11.931179
9     11.575698
10    11.226457
11    13.126587
12    10.682489
Name: windspeed, dtype: float64

weather 컬럼

- weather 종류 별 데이터 건수 출력

In [130]:
df.weather.value_counts()

1    7192
2    2834
3     859
4       1
Name: weather, dtype: int64

humidity 컬럼

- 2011년 평균 습도 출력

- 2012년 평균 습도 출력

- 연도와 관계없이 월별 평균 습도 출력

- 표준편차 출력(연도별)

In [54]:
df.groupby(df['datetime'].dt.year)['humidity'].mean()[2011]

63.40501659904094

In [55]:
df.groupby(df['datetime'].dt.year)['humidity'].mean()[2012]

60.37957540263543

In [72]:
df.groupby(df.datetime.dt.month)['humidity'].mean()

datetime
1     55.911765
2     56.296337
3     56.678135
4     55.697470
5     68.084430
6     58.759868
7     58.402412
8     63.010965
9     70.980198
10    69.412733
11    60.722283
12    68.383772
Name: humidity, dtype: float64

In [74]:
df.groupby(df.datetime.dt.year)['humidity'].std()

datetime
2011    19.780518
2012    18.578008
Name: humidity, dtype: float64

datetime 컬럼

- 월별(01~12) 평균 count 출력

- 일별(01~19) 평균 count 출력

- 시각별(0~23) 평균 count 출력

- 평균 count값이 가장 큰 월 출력

- 평균 count값이 가장 큰 시각 출력


In [67]:
df.groupby(df.datetime.dt.month)['count'].mean()

datetime
1      90.366516
2     110.003330
3     148.169811
4     184.160616
5     219.459430
6     242.031798
7     235.325658
8     234.118421
9     233.805281
10    227.699232
11    193.677278
12    175.614035
Name: count, dtype: float64

In [69]:
df.groupby(df.datetime.dt.day)['count'].mean()

datetime
1     180.333913
2     183.910995
3     194.696335
4     195.705575
5     189.765217
6     189.860140
7     183.773519
8     179.041812
9     187.897391
10    195.183566
11    195.679577
12    190.675393
13    194.160279
14    195.829268
15    201.527875
16    191.353659
17    205.660870
18    192.605684
19    192.311847
Name: count, dtype: float64

In [70]:
df.groupby(df.datetime.dt.time)['count'].mean()

datetime
00:00:00     55.138462
01:00:00     33.859031
02:00:00     22.899554
03:00:00     11.757506
04:00:00      6.407240
05:00:00     19.767699
06:00:00     76.259341
07:00:00    213.116484
08:00:00    362.769231
09:00:00    221.780220
10:00:00    175.092308
11:00:00    210.674725
12:00:00    256.508772
13:00:00    257.787281
14:00:00    243.442982
15:00:00    254.298246
16:00:00    316.372807
17:00:00    468.765351
18:00:00    430.859649
19:00:00    315.278509
20:00:00    228.517544
21:00:00    173.370614
22:00:00    133.576754
23:00:00     89.508772
Name: count, dtype: float64

In [77]:
df.groupby(df.datetime.dt.month)['count'].mean().idxmax()

6

In [78]:
df.groupby(df.datetime.dt.time)['count'].mean().idxmax()

datetime.time(17, 0)

상관분석 

- temp와 count 간 상관 계수 출력

- humidity와 count 간 상관 계수 출력

- weather와 count 간 상관 계수 출력

- windspeed와 count 간 상관 계수 출력

- 위 4개의 features 중에서 상관 계수가 가장 큰 feature 출력

In [120]:
np.corrcoef(df['temp'],df['count'])

array([[1.        , 0.39445364],
       [0.39445364, 1.        ]])

In [121]:
np.corrcoef(df['humidity'],df['count'])

array([[ 1.        , -0.31737148],
       [-0.31737148,  1.        ]])

In [122]:
np.corrcoef(df['weather'],df['count'])

array([[ 1.       , -0.1286552],
       [-0.1286552,  1.       ]])

In [123]:
np.corrcoef(df['windspeed'],df['count'])

array([[1.        , 0.10136947],
       [0.10136947, 1.        ]])

In [129]:
cor = df[['count','temp','humidity','weather','windspeed']].corr()
print(cor)
abs(cor.where(cor!=1,np.nan)['count']).idxmax()

              count      temp  humidity   weather  windspeed
count      1.000000  0.394454 -0.317371 -0.128655   0.101369
temp       0.394454  1.000000 -0.064949 -0.055035  -0.017852
humidity  -0.317371 -0.064949  1.000000  0.406244  -0.318607
weather   -0.128655 -0.055035  0.406244  1.000000   0.007261
windspeed  0.101369 -0.017852 -0.318607  0.007261   1.000000


'temp'